image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS:   "4333796"
  TERM: "dumb"

before_script:
  # NodeJS installation
  - curl -sL https://deb.nodesource.com/setup_11.x | bash -
  - apt install nodejs
  - node --version
  - npm --version
    
stages:
  - test
  - e2e

# Define the jobs here
unitTests:
  stage: test
  script:
    - npm install
    - npm install --chromedriver_version="2.24"
    - npx eslint lib/ test/
    - npx gulp unit-test
    - npm run test:server

e2eCommandsTest:
  stage: e2e
  include: ./gitlab/.android-before-script-template.yml
  script:
    - npm run build
    - echo "NOT READY YET"